spring:
  application:
    name: sms
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/sms
    username: postgres
    password: postgres

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  jpa.properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE